version: "3"

services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.7
    environment:
      - RABBITMQ_MNESIA_BASE=/var/lib/rabbitmq/mnesia
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia

  db:
    restart: always
    image: mongo:4
    volumes:
      - ./data/nosql:/data/db

  cam_dash:
    restart: always
    build: .
    command: python3 manage.py runserver 127.0.0.1:3000
    volumes:
      - .:/camera_dashboard
    depends_on:
      - "db"

  celery:
    restart: always
    build: .
    volumes:
      - .:/camera_dashboard
    depends_on:
      - "rabbitmq"
      - "cam_dash"
    environment:
      - LOG_STREAM=Celery
    command: celery -A camera_dashboard worker -l INFO -c 200

  celery_beat:
    restart: always
    build: .
    volumes:
      - .:/camera_dashboard
    depends_on:
      - "celery"
    environment:
      - LOG_STREAM=CeleryBeat
    command: celery beat -A camera_dashboard -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler